// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCenxtN3JENsOesxoou2p3PSQ1jmvsFXpA',
    appId: '1:537172708088:web:eed40a896f85790a1b490d',
    messagingSenderId: '537172708088',
    projectId: 'mynotes-flutter-dcb94',
    authDomain: 'mynotes-flutter-dcb94.firebaseapp.com',
    storageBucket: 'mynotes-flutter-dcb94.appspot.com',
    measurementId: 'G-EF865G8P1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnyQFEmpphF3_hoV9y8nMP2aQN29OkCGY',
    appId: '1:537172708088:android:977681d26b1ff8561b490d',
    messagingSenderId: '537172708088',
    projectId: 'mynotes-flutter-dcb94',
    storageBucket: 'mynotes-flutter-dcb94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-lJnEAEy5MEFD4PUogROp6vDbSrLQI5Y',
    appId: '1:537172708088:ios:e419b5eaf87f72e01b490d',
    messagingSenderId: '537172708088',
    projectId: 'mynotes-flutter-dcb94',
    storageBucket: 'mynotes-flutter-dcb94.appspot.com',
    iosClientId: '537172708088-mqg35qbchvggi7t9f4jltipdbn3b3dhb.apps.googleusercontent.com',
    iosBundleId: 'com.tipre.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-lJnEAEy5MEFD4PUogROp6vDbSrLQI5Y',
    appId: '1:537172708088:ios:e419b5eaf87f72e01b490d',
    messagingSenderId: '537172708088',
    projectId: 'mynotes-flutter-dcb94',
    storageBucket: 'mynotes-flutter-dcb94.appspot.com',
    iosClientId: '537172708088-mqg35qbchvggi7t9f4jltipdbn3b3dhb.apps.googleusercontent.com',
    iosBundleId: 'com.tipre.mynotes',
  );
}
